### ISSUE TITLE
Access via role in Shell

### ISSUE THREAD

**Issue by BastiAsam** [dtylman/AWSRetriever#1]
Hi Denny,
thanks for the great Tool! I encountered a problem when trying to access via role.
First I got the Error Message about the missing AWSSDK.SecurityToken.
![AWSRetriever_Error](https://user-images.githubusercontent.com/50922671/58192057-336f2d80-7cc0-11e9-9660-f4cedb0dbb06.PNG)

I could resolve this by manually copying the dll to the AWSRetriever folder. Then it works in the GUI.

But what I really wanted to do was to use your tool via shell.
It's hard to get it to run as role, but with the -c option I was able to. AwsUser set to role name as in the AWS CLI environment.
That way it starts running, till it hits this exception:

`Unhandled Exception: System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.WriteLine(String value)
   at Retriever.ConsoleScanner.Progress_ProgressChanged(Object sender, OperationResult e)
   at System.Progress`1.InvokeHandlers(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

Maybe you can have a look at it?
Thank you so much!
Basti

**Comment by dtylman** [comment]
Hi,

I think I fixed those issues. I am a bit short in time now, and haven't tested it properly.

Please take: https://github.com/dtylman/AWSRetriever/releases/download/rc3/AWSRetriever_0_1_0_13.zip and see if it works for you.

If so, please close the issue.

Danny

**Comment by BastiAsam** [comment]
Hi Danny,
thank you so much for looking into it! The problem with the dll is fixed and in the GUI it looks fine, but I still get a "Cannot access a closed file" Error when running it in the shell.
The command I am running looks like:
./AWSRetriever.exe -c user.config.js -r -p test.profile.js -o resources.js

I attached the profile I am running. Maybe you can recreate the error.

Also the user config file looks wrong "ConcurrentConnecitons". But editing it didn't change the behavior. To complete it I attached it as well.

[user.config.txt](https://github.com/dtylman/AWSRetriever/files/3224432/user.config.txt)
[test.profile.txt](https://github.com/dtylman/AWSRetriever/files/3224433/test.profile.txt)

If you need anything more, let me know.
Thanks again!
Basti

**Comment by dtylman** [comment]
Fixed the 'connections' typo.

I tried this with the profile and config you have provided. I cannot reproduce this :(

I use the accesskey and not user in AWS config, but I don't think it should make a diffrence. 

You say the GUI works for you. What OS / environment you're using?

**Comment by BastiAsam** [comment]
I think it was because of my profile. I cleared it manually to have everything deselected and then selected some in your Profile Manager and saved it. 
When I use this profile I get the Error. When I use an other one it works fine!
Thank you very much!

**Comment by dtylman** [comment]
:+1:
